### PR TITLE
Update the lab docs and related code

### PR DESCRIPTION
**Pull request by chenxizhang**
correct the prompt to enable developer mode

### CODE REVIEW

**Comment by chenxizhang** [comment]
@rabwill  Hi Rabia, thanks for your great work on this camp docs especially the hands-on lab part, I am going to introduce to more developers (inside or outside Microsoft) to try the copilot agent,  I will much prefer them to follow the guidance of your doc so I went through all the steps very carefully, and I'd propose some updates on the doc or even the code. FYI, thanks

**Comment by chenxizhang** [comment]
I will spend more time on lab-e4,5,6, and share the feedback to you.

image

**Comment by chenxizhang** [comment]
Another feedback
1. In lab-e3, I saw you are using the OpenAPI specification newest version 3.0.1, which is not align with the default template of TTK generated, they are using the 3.0.0, and it was yml file. I am not sure if this can introduce a little bit confusing to developers, especially if they start with the TTK template directly.
2. I'd suggest to introduce the "https://m365.cloud.microsoft/chat" to debug the copilot agent, instead of "https://teams.microsoft.com/v2" which is very slow, at least per my experience.
3. In the lab -e3, step 5, if I really remove the code you mentioned, it will get failed when I try to debug the app. You might want to double confirm it

**Comment by rabwill** [comment]
Thanks @chenxizhang for all the feedback let me go through them

**Comment by rabwill** [comment]
The PR looks great, but could you open these comments as separate issue so we can work on them thanks @chenxizhang I dont want it to be lost when I close this PR.

**Pull request merged**
